"""
Seeds the database with the Vendor, PO, and Contract that match
the sample invoice generated by generate_sample_invoice.py.

Run once from the backend/ directory:
    python seed_test_data.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import SessionLocal, engine, Base
import models.models  # ensures all tables are registered
from models.models import Vendor, PurchaseOrder, Contract

Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    # --- Vendor ---
    existing_vendor = db.query(Vendor).filter(Vendor.vendor_code == "DELL-001").first()
    if existing_vendor:
        print("INFO: Vendor DELL-001 already exists -- skipping.")
        vendor = existing_vendor
    else:
        vendor = Vendor(name="Dell Technologies Inc.", vendor_code="DELL-001")
        db.add(vendor)
        db.flush()
        print(f"OK: Vendor created: {vendor.name} (id={vendor.id})")

    # --- Purchase Order ---
    existing_po = db.query(PurchaseOrder).filter(PurchaseOrder.po_number == "PO-DELL-2024").first()
    if existing_po:
        print("INFO: PO PO-DELL-2024 already exists -- skipping.")
    else:
        po = PurchaseOrder(
            po_number="PO-DELL-2024",
            vendor_id=vendor.id,
            total_amount=10775.00,
            status="OPEN",
            line_items=[
                {
                    "description": "Dell Latitude 5540 Laptop",
                    "quantity": 10.0,
                    "unit_price": 850.00,
                    "total": 8500.00,
                },
                {
                    "description": 'Dell 27" Monitor P2723D',
                    "quantity": 5.0,
                    "unit_price": 320.00,
                    "total": 1600.00,
                },
                {
                    "description": "Dell Wireless Keyboard & Mouse",
                    "quantity": 15.0,
                    "unit_price": 45.00,
                    "total": 675.00,
                },
            ],
        )
        db.add(po)
        print("OK: PO created: PO-DELL-2024 (total $10,775.00)")

    # --- Contract ---
    existing_contract = db.query(Contract).filter(Contract.contract_number == "CTR-DELL-2024").first()
    if existing_contract:
        print("INFO: Contract CTR-DELL-2024 already exists -- skipping.")
    else:
        contract = Contract(
            contract_number="CTR-DELL-2024",
            vendor_id=vendor.id,
            max_amount=50000.00,
        )
        db.add(contract)
        print("OK: Contract created: CTR-DELL-2024 (max $50,000.00)")

    db.commit()
    print("")
    print("Database seeded. Upload sample_invoice_clean.pdf -- expected: STRAIGHT_THROUGH")

except Exception as exc:
    db.rollback()
    print(f"ERROR: {exc}")
    raise
finally:
    db.close()
